markdown: kramdown
highlighter: rouge
permalink: /article/:title
paginate: 5
exclude: [excludethis]
timezone: Asia/Jakarta

gems:
  - jekyll-redirect-from
  

# variables
title: NNDDCC
tagline: Personal Website of Endy Tjahjono



description: Personal Web Pages of Endy Tjahjono
google_analytics: 
show_downloads: true
theme: jekyll-theme-time-machine